"""Social post generation pipeline — DeepSeek as True Creative Director

ARCHITECTURE:
    Minimal User Input (Company Core + Campaign Goal)
      ↓
    DeepSeek - Strategic Analysis
    - Researches company context
    - Understands industry trends
    - Analyzes target audience
      ↓
    DeepSeek - Content Generation
    - Creates unique post concepts
    - Writes headlines, supporting text, CTAs
    - Adapts tone per content type
      ↓
    DeepSeek - Visual Strategy
    - Decides layout per post
    - Creates visual bible
    - Generates background prompts
      ↓
    Image Generation API
      ↓
    Professional Renderer (Brand Consistent)
      ↓
    Final Posts

DeepSeek is the BRAIN - not just formatting hardcoded data!
"""
from __future__ import annotations

import asyncio
import base64
import json
import re
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import wrap
from typing import Optional, List as ListType
from datetime import datetime

import httpx

try:
    from PIL import Image, ImageDraw, ImageFont, ImageFilter
except ImportError:
    raise SystemExit("Install Pillow: pip install Pillow httpx")


# ---------------------------------------------------------------------------
# .env loader
# ---------------------------------------------------------------------------

def load_env() -> dict[str, str]:
    env_path = Path(__file__).parent / ".env"
    if not env_path.exists():
        raise SystemExit(".env not found")
    env: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")
    return env


ENV = load_env()
DEEPSEEK_KEY = ENV.get("DEEPSEEK_API_KEY", "")

if not DEEPSEEK_KEY:
    raise SystemExit("DEEPSEEK_API_KEY missing in .env")

# Image generation keys
GEMINI_KEY = ENV.get("GEMINI_API_KEY", "")
GEMINI_KEY2 = ENV.get("GEMINI_API_KEY2", "")
OPENAI_KEY = ENV.get("OPENAI_API_KEY", "")
MINIMAX_KEY = ENV.get("MINIMAX_API_KEY", "")
ZAI_KEY = ENV.get("ZAI_API_KEY", "")
OPENROUTER_KEY = ENV.get("OPENROUTER_API_KEY", "")
OPENROUTER_KEY2 = ENV.get("OPENROUTER_API_KEY2", "")

if not any([GEMINI_KEY, OPENAI_KEY, MINIMAX_KEY, ZAI_KEY, OPENROUTER_KEY]):
    raise SystemExit("No image generation API key found in .env")

try:
    from google import genai
    from google.genai import types
    GEMINI_SDK_AVAILABLE = True
except ImportError:
    GEMINI_SDK_AVAILABLE = False

try:
    from openai import OpenAI
    OPENAI_SDK_AVAILABLE = True
except ImportError:
    OPENAI_SDK_AVAILABLE = False

try:
    from zai import ZaiClient
    ZAI_SDK_AVAILABLE = True
except ImportError:
    ZAI_SDK_AVAILABLE = False


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class BrandCore:
    """Core brand information - user provides this"""
    company_name: str
    industry: str
    primary_color: str
    secondary_color: str
    accent_color: str
    font_style: str
    brand_tone: str
    visual_style: str
    tagline: str
    website_url: str
    target_audience: str
    key_products: ListType[str]
    brand_values: ListType[str]


@dataclass
class CampaignGoal:
    """What the user wants to achieve"""
    objective: str  # e.g., "hiring", "product_launch", "awareness", "engagement"
    key_messages: ListType[str]
    campaign_tone: str
    target_platform: str  # LinkedIn, Instagram, Twitter, etc.
    number_of_posts: int = 8


@dataclass
class GeneratedPost:
    """Complete post generated by DeepSeek"""
    id: int
    content_type: str
    headline: str
    supporting_text: str
    cta: str
    visual_description: str
    mood: str
    layout_strategy: str
    background_prompt: str
    features: ListType[str] = field(default_factory=list)
    stats: dict = field(default_factory=dict)
    quote: str = ""
    
    # Will be filled during generation
    background_image_bytes: Optional[bytes] = None
    final_path: Optional[Path] = None


# ---------------------------------------------------------------------------
# DEFAULT BRAND (User can edit this in the code or later via CLI)
# ---------------------------------------------------------------------------

DEFAULT_BRAND = BrandCore(
    company_name="Trackin",
    industry="Transit Technology / Urban Mobility",
    primary_color="#0057FF",
    secondary_color="#FFFFFF",
    accent_color="#FF6B35",
    font_style="Inter",
    brand_tone="Professional, Innovative, Trustworthy",
    visual_style="Modern SaaS, Clean, Tech-forward",
    tagline="Move Smarter. Move Together.",
    website_url="WWW.TRACKIN.TECH",
    target_audience="Urban commuters, transit operators, fleet managers",
    key_products=["Real-time bus tracking", "Fleet management system", "Rider mobile app", "Analytics dashboard"],
    brand_values=["Reliability", "Innovation", "Accessibility", "Safety"]
)

DEFAULT_GOAL = CampaignGoal(
    objective="brand_awareness_and_engagement",
    key_messages=[
        "Making urban transit smarter",
        "Real-time visibility for commuters",
        "Efficiency for transit operators"
    ],
    campaign_tone="Inspiring, Educational, Trust-building",
    target_platform="LinkedIn",
    number_of_posts=8
)


# ---------------------------------------------------------------------------
# DeepSeek API - The Creative Brain
# ---------------------------------------------------------------------------

async def deepseek_call(system: str, user: str, max_tokens: int = 800) -> str:
    """Call DeepSeek API"""
    async with httpx.AsyncClient(timeout=90.0) as client:
        resp = await client.post(
            "https://api.deepseek.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {DEEPSEEK_KEY}", "Content-Type": "application/json"},
            json={
                "model": "deepseek-chat",
                "max_tokens": max_tokens,
                "temperature": 0.8,  # Slight creativity
                "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
            },
        )
    data = resp.json()
    if "error" in data:
        raise RuntimeError(f"DeepSeek error: {data['error']}")
    return data["choices"][0]["message"]["content"].strip()


def parse_json(raw: str) -> dict:
    """Extract JSON from LLM response"""
    clean = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
    return json.loads(clean)


async def research_company_context(brand: BrandCore, goal: CampaignGoal) -> str:
    """DeepSeek researches and understands the company deeply"""
    system = """You are a Senior Brand Strategist. Analyze the company and campaign goal.
    Think like a creative director preparing for a campaign.
    Return your analysis as a JSON object."""
    
    user = f"""
COMPANY: {brand.company_name}
INDUSTRY: {brand.industry}
BRAND TONE: {brand.brand_tone}
VISUAL STYLE: {brand.visual_style}
TAGLINE: {brand.tagline}
TARGET AUDIENCE: {brand.target_audience}
KEY PRODUCTS: {', '.join(brand.key_products)}
BRAND VALUES: {', '.join(brand.brand_values)}

CAMPAIGN OBJECTIVE: {goal.objective}
KEY MESSAGES: {', '.join(goal.key_messages)}
CAMPAIGN TONE: {goal.campaign_tone}
TARGET PLATFORM: {goal.target_platform}

Analyze this company and provide:
{{
  "company_voice": "How this brand speaks (2-3 sentences)",
  "emotional_triggers": ["List of 3-4 emotions that resonate with their audience"],
  "visual_themes": ["List of 3-4 visual themes that represent the brand"],
  "content_opportunities": ["List of 3-4 angles/messages that would work well"],
  "differentiators": "What makes this brand unique"
}}

Think deeply about what makes this company special.
"""
    raw = await deepseek_call(system, user, max_tokens=600)
    return parse_json(raw)


async def generate_post_concepts(brand: BrandCore, goal: CampaignGoal, context: dict, num_posts: int) -> ListType[dict]:
    """DeepSeek generates creative post concepts from scratch"""
    system = """You are a Senior Creative Director and Copywriter.
    Generate UNIQUE, ENGAGING social media post concepts.
    Each post should have a different angle, emotion, and visual approach.
    Return ONLY valid JSON array."""
    
    user = f"""
CAMPAIGN CONTEXT:
Company: {brand.company_name}
Industry: {brand.industry}
Brand Values: {', '.join(brand.brand_values)}
Key Products: {', '.join(brand.key_products)}
Target Audience: {brand.target_audience}

Campaign Goal: {goal.objective}
Key Messages: {', '.join(goal.key_messages)}
Campaign Tone: {goal.campaign_tone}
Platform: {goal.target_platform}

Company Voice: {context.get('company_voice', 'Professional yet approachable')}
Emotional Triggers: {context.get('emotional_triggers', ['trust', 'innovation'])}
Visual Themes: {context.get('visual_themes', ['modern', 'clean'])}
Differentiators: {context.get('differentiators', 'Innovative transit technology')}

Generate {num_posts} UNIQUE post concepts. Each post should:
- Have a different content type (hiring, announcement, educational, inspirational, product, case study, testimonial, industry_insight)
- Have a unique angle and emotion
- Be appropriate for {goal.target_platform}
- Include a compelling headline (max 40 chars)
- Include 1-2 sentence supporting text
- Include a clear CTA
- Suggest a visual direction (1 sentence)

Return as JSON array:
[
  {{
    "content_type": "e.g., announcement, educational, inspirational, product, hiring, case_study",
    "headline": "Short, punchy headline",
    "supporting_text": "Engaging supporting copy",
    "cta": "Action button text",
    "visual_theme": "From the visual themes above",
    "emotional_angle": "Primary emotion this post should evoke"
  }}
]

Make each post genuinely different and creative!
"""
    raw = await deepseek_call(system, user, max_tokens=2000)
    return parse_json(raw)


async def enrich_post_content(post_concept: dict, brand: BrandCore, goal: CampaignGoal) -> dict:
    """DeepSeek adds features, stats, quotes to make each post rich"""
    system = """You are a Content Strategist. Enhance this post with specific details.
    Add relevant statistics, features, or a customer quote.
    Return ONLY valid JSON."""
    
    user = f"""
Brand: {brand.company_name}
Industry: {brand.industry}
Key Products: {', '.join(brand.key_products)}
Campaign Goal: {goal.objective}

POST CONCEPT:
Content Type: {post_concept.get('content_type')}
Headline: {post_concept.get('headline')}
Supporting Text: {post_concept.get('supporting_text')}
Emotional Angle: {post_concept.get('emotional_angle')}

Enhance this post by adding:
{{
  "enhanced_headline": "Refined headline (if needed)",
  "enhanced_supporting_text": "Expanded supporting text with details",
  "features": ["List of 2-4 relevant features or benefits"],
  "stats": {{"key1": "value1", "key2": "value2"}} (add realistic industry stats if relevant),
  "quote": "Optional customer or expert quote (30-40 words)"
}}

Keep the brand voice consistent. Make statistics believable for the industry.
"""
    raw = await deepseek_call(system, user, max_tokens=800)
    enriched = parse_json(raw)
    
    # Merge with original
    return {
        "content_type": post_concept.get('content_type'),
        "headline": enriched.get('enhanced_headline', post_concept.get('headline')),
        "supporting_text": enriched.get('enhanced_supporting_text', post_concept.get('supporting_text')),
        "cta": post_concept.get('cta'),
        "features": enriched.get('features', []),
        "stats": enriched.get('stats', {}),
        "quote": enriched.get('quote', ''),
        "visual_theme": post_concept.get('visual_theme'),
        "emotional_angle": post_concept.get('emotional_angle')
    }


async def determine_layout_strategy(post: dict, brand: BrandCore) -> dict:
    """DeepSeek decides optimal layout for this specific post"""
    system = """You are a Senior Graphic Designer.
    Based on the content, decide the best layout strategy.
    Return ONLY valid JSON."""
    
    user = f"""
Content Type: {post.get('content_type')}
Headline: {post.get('headline')}
Features: {len(post.get('features', []))} features
Has Stats: {bool(post.get('stats'))}
Has Quote: {bool(post.get('quote'))}
Brand Visual Style: {brand.visual_style}

Choose layout strategy:
- hero_centered: Big central message (announcements, celebrations)
- feature_list: Bullet points (product features, hiring benefits)
- stats_dense: Numbers prominent (achievements, growth metrics)
- split_vertical: Image left, text right (balanced storytelling)
- quote_centered: Testimonial style
- educational: Problem-solution format

Return JSON:
{{
  "layout_strategy": "chosen strategy",
  "visual_hierarchy": "text_dominant OR image_dominant OR balanced",
  "headline_position": "top OR center OR bottom",
  "content_density": "minimal OR standard OR dense",
  "background_role": "atmospheric OR contextual OR abstract"
}}
"""
    raw = await deepseek_call(system, user, max_tokens=300)
    return parse_json(raw)


async def create_visual_bible(post: dict, layout: dict, brand: BrandCore, goal: CampaignGoal) -> dict:
    """DeepSeek as Creative Director - defines visual language"""
    system = """You are a Creative Director specializing in brand-consistent design.
    Create a unique visual treatment for this specific post.
    Return ONLY valid JSON."""
    
    user = f"""
BRAND: {brand.company_name}
Primary Color: {brand.primary_color}
Accent Color: {brand.accent_color}
Font Style: {brand.font_style}
Visual Style: {brand.visual_style}

POST:
Content Type: {post.get('content_type')}
Headline: {post.get('headline')}
Emotional Angle: {post.get('emotional_angle')}
Features: {', '.join(post.get('features', [])[:2])}

LAYOUT STRATEGY: {layout.get('layout_strategy')}
BACKGROUND ROLE: {layout.get('background_role')}

Create Visual Bible:
{{
  "mood": "Emotional atmosphere (3-4 words)",
  "color_palette": ["#hex1", "#hex2", "#hex3"],
  "typography": "Font weights and sizes (e.g., 'Bold 56pt headlines, Regular 24pt body')",
  "composition": "How elements are arranged",
  "lighting": "Lighting style for background",
  "texture": "Texture or pattern overlay",
  "background_description": "DETAILED scene description for AI image generation"
}}

RULES:
- ALWAYS include {brand.primary_color} in palette
- Typography must reference {brand.font_style}
- Background must leave space for text based on layout strategy
- Make the scene UNIQUE to this content type
- For transit/tech: Think modern, urban, futuristic, or abstract tech
- NO TEXT in the background description
"""
    raw = await deepseek_call(system, user, max_tokens=600)
    return parse_json(raw)


async def generate_background_prompt(post: dict, bible: dict, layout: dict, brand: BrandCore) -> str:
    """Create detailed prompt for image generation"""
    system = """You are a Prompt Engineer for AI image generation.
    Create a detailed, cinematic prompt for the background image.
    Return ONLY the prompt string."""
    
    user = f"""
Brand: {brand.company_name}
Industry: {brand.industry}
Content Type: {post.get('content_type')}
Mood: {bible.get('mood')}
Visual Theme: {post.get('visual_theme')}
Colors: {', '.join(bible.get('color_palette', []))}
Layout Strategy: {layout.get('layout_strategy')}
Background Role: {layout.get('background_role')}
Scene Description: {bible.get('background_description')}

Create an image generation prompt (max 150 words):
- High quality, cinematic, {brand.visual_style} style
- Leave space for text overlay (important for {layout.get('layout_strategy')} layout)
- Match the mood: {bible.get('mood')}
- Use colors from palette
- NO text, NO UI elements, NO people reading/holding phones
- Focus on the scene described
- Professional, brand-appropriate quality
"""
    return await deepseek_call(system, user, max_tokens=300)


# ---------------------------------------------------------------------------
# Image Generation Providers (Keep as is - working fine)
# ---------------------------------------------------------------------------

class GeminiImageGenerator:
    @staticmethod
    async def generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        if not GEMINI_SDK_AVAILABLE:
            raise RuntimeError("Google Gemini SDK not installed")
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, GeminiImageGenerator._sync_generate, prompt, api_key, aspect_ratio)
    
    @staticmethod
    def _sync_generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        try:
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model="gemini-2.5-flash-image",
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=1.0, top_p=0.95,
                    response_modalities=["IMAGE"],
                    image_config=types.ImageConfig(aspect_ratio=aspect_ratio)
                )
            )
            if hasattr(response, 'candidates') and response.candidates:
                for candidate in response.candidates:
                    if hasattr(candidate, 'content') and candidate.content:
                        for part in candidate.content.parts:
                            if hasattr(part, 'inline_data') and part.inline_data:
                                return part.inline_data.data
            raise RuntimeError("No image data found")
        except Exception as e:
            raise RuntimeError(f"Gemini error: {str(e)}")


class OpenAIImageGenerator:
    @staticmethod
    async def generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        if not OPENAI_SDK_AVAILABLE:
            raise RuntimeError("OpenAI SDK not installed")
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, OpenAIImageGenerator._sync_generate, prompt, api_key, aspect_ratio)
    
    @staticmethod
    def _sync_generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        try:
            client = OpenAI(api_key=api_key)
            size_map = {"1:1": "1024x1024", "3:4": "1024x1792", "16:9": "1792x1024"}
            size = size_map.get(aspect_ratio, "1024x1024")
            response = client.images.generate(
                model="dall-e-3", prompt=prompt, size=size, quality="standard", n=1, response_format="b64_json"
            )
            if response.data and response.data[0].b64_json:
                return base64.b64decode(response.data[0].b64_json)
            raise RuntimeError("No image data")
        except Exception as e:
            raise RuntimeError(f"OpenAI error: {str(e)}")


class MiniMaxImageGenerator:
    @staticmethod
    async def generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        url = "https://api.minimax.io/v1/image_generation"
        headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        payload = {"model": "image-01", "prompt": prompt, "aspect_ratio": aspect_ratio, "response_format": "url"}
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(url, headers=headers, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"MiniMax error {resp.status_code}")
            data = resp.json()
            urls = data.get("data", {}).get("image_urls", [])
            if not urls:
                raise RuntimeError("No image URL")
            img_resp = await client.get(urls[0])
            img_resp.raise_for_status()
            return img_resp.content


class ZAIImageGenerator:
    @staticmethod
    async def generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        if not ZAI_SDK_AVAILABLE:
            raise RuntimeError("Z.AI SDK not installed")
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, ZAIImageGenerator._sync_generate, prompt, api_key, aspect_ratio)
    
    @staticmethod
    def _sync_generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        try:
            client = ZaiClient(api_key=api_key)
            response = client.images.generations(model="glm-image", prompt=prompt)
            if response.data and len(response.data) > 0 and response.data[0].url:
                import requests
                img_response = requests.get(response.data[0].url, timeout=60)
                img_response.raise_for_status()
                return img_response.content
            raise RuntimeError("No image URL")
        except Exception as e:
            raise RuntimeError(f"Z.AI error: {str(e)}")


class OpenRouterImageGenerator:
    @staticmethod
    async def generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, OpenRouterImageGenerator._sync_generate, prompt, api_key, aspect_ratio)
    
    @staticmethod
    def _sync_generate(prompt: str, api_key: str, aspect_ratio: str = "1:1") -> bytes:
        try:
            url = "https://openrouter.ai/api/v1/chat/completions"
            headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            payload = {"model": "google/gemini-2.5-flash-image", "messages": [{"role": "user", "content": prompt}], "modalities": ["image"]}
            import requests
            response = requests.post(url, headers=headers, json=payload, timeout=120)
            response.raise_for_status()
            result = response.json()
            if result.get("choices"):
                message = result["choices"][0]["message"]
                if message.get("images"):
                    for image in message["images"]:
                        image_url = image["image_url"]["url"]
                        if image_url.startswith("data:image"):
                            return base64.b64decode(image_url.split(",")[1])
                        img_response = requests.get(image_url, timeout=60)
                        img_response.raise_for_status()
                        return img_response.content
            raise RuntimeError("No image data")
        except Exception as e:
            raise RuntimeError(f"OpenRouter error: {str(e)}")


def save_bytes_as_image(data: bytes, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)


# ---------------------------------------------------------------------------
# Professional Renderer (Brand Consistent)
# ---------------------------------------------------------------------------

def hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def get_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates_bold = [
        "C:/Windows/Fonts/Inter-Bold.ttf", "C:/Windows/Fonts/arialbd.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ]
    candidates_regular = [
        "C:/Windows/Fonts/Inter-Regular.ttf", "C:/Windows/Fonts/arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    candidates = candidates_bold if bold else candidates_regular
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except (IOError, OSError):
            continue
    return ImageFont.load_default()


def render_professional_post(
    bg_bytes: bytes,
    post: GeneratedPost,
    brand: BrandCore,
    layout_strategy: str,
    bible: dict,
    out_path: Path,
    canvas_size: int = 1080,
) -> Path:
    """Render final post with consistent brand elements"""
    
    # Load background from bytes
    from io import BytesIO
    bg = Image.open(BytesIO(bg_bytes)).convert("RGBA")
    bg = bg.resize((canvas_size, canvas_size), Image.LANCZOS)
    
    primary_rgb = hex_to_rgb(brand.primary_color)
    accent_rgb = hex_to_rgb(brand.accent_color)
    white = hex_to_rgb(brand.secondary_color)
    
    # ============ CONSISTENT ELEMENTS ============
    
    # TOP BRAND BAR
    top_bar_h = int(canvas_size * 0.09)
    top_bar = Image.new("RGBA", (canvas_size, top_bar_h), (*primary_rgb, 235))
    bg.paste(top_bar, (0, 0), mask=top_bar)
    
    draw = ImageDraw.Draw(bg)
    
    # Company name
    brand_font = get_font(int(canvas_size * 0.034), bold=True)
    brand_x = int(canvas_size * 0.05)
    brand_y = int(top_bar_h * 0.25)
    draw.text((brand_x, brand_y), brand.company_name.upper(), font=brand_font, fill=white)
    
    # Tagline
    if brand.tagline:
        tag_font = get_font(int(canvas_size * 0.018))
        tag_w = draw.textlength(brand.tagline, font=tag_font)
        draw.text(
            (canvas_size - tag_w - int(canvas_size * 0.05), brand_y + 6),
            brand.tagline, font=tag_font, fill=(*white, 200)
        )
    
    # BOTTOM FOOTER
    footer_h = int(canvas_size * 0.06)
    footer_y = canvas_size - footer_h
    footer_bg = Image.new("RGBA", (canvas_size, footer_h), (*primary_rgb, 220))
    bg.paste(footer_bg, (0, footer_y), mask=footer_bg)
    
    footer_font = get_font(int(canvas_size * 0.022), bold=True)
    footer_w = draw.textlength(brand.website_url, font=footer_font)
    draw.text(
        ((canvas_size - footer_w) // 2, footer_y + int(footer_h * 0.28)),
        brand.website_url, font=footer_font, fill=white
    )
    
    # ============ CONTENT ZONE ============
    
    content_top = top_bar_h + int(canvas_size * 0.03)
    content_bottom = footer_y - int(canvas_size * 0.03)
    content_height = content_bottom - content_top
    
    # Semi-transparent overlay
    overlay = Image.new("RGBA", (canvas_size, content_height), (0, 0, 0, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    
    if layout_strategy in ["hero_centered", "announcement"]:
        for y in range(content_height):
            alpha = int(120 * (1 - y / content_height * 0.6))
            overlay_draw.line([(0, y), (canvas_size, y)], fill=(0, 0, 0, alpha))
    else:
        overlay_draw.rectangle([(0, 0), (canvas_size, content_height)], fill=(0, 0, 0, 140))
    
    bg.paste(overlay, (0, content_top), mask=overlay)
    
    # ============ RENDER CONTENT ============
    
    pad_x = int(canvas_size * 0.07)
    text_y = content_top + int(canvas_size * 0.04)
    
    if layout_strategy == "hero_centered":
        # Large centered text
        headline_size = int(canvas_size * 0.085)
        headline_font = get_font(headline_size, bold=True)
        headline_w = draw.textlength(post.headline, font=headline_font)
        headline_x = (canvas_size - headline_w) // 2
        draw.text((headline_x, text_y), post.headline, font=headline_font, fill=white)
        text_y += int(canvas_size * 0.12)
        
        support_font = get_font(int(canvas_size * 0.032))
        wrapped = wrap(post.supporting_text, width=35)
        for line in wrapped[:2]:
            line_w = draw.textlength(line, font=support_font)
            line_x = (canvas_size - line_w) // 2
            draw.text((line_x, text_y), line, font=support_font, fill=(*white, 220))
            text_y += int(canvas_size * 0.045)
            
    elif layout_strategy == "feature_list":
        # Features with bullets
        headline_font = get_font(int(canvas_size * 0.058), bold=True)
        draw.text((pad_x, text_y), post.headline, font=headline_font, fill=white)
        text_y += int(canvas_size * 0.08)
        
        bullet_font = get_font(int(canvas_size * 0.028))
        features = post.features if post.features else [post.supporting_text[:50]]
        for i, feature in enumerate(features[:6]):
            draw.text((pad_x, text_y), f"• {feature}", font=bullet_font, fill=(*white, 220))
            text_y += int(canvas_size * 0.045)
            
    elif layout_strategy == "stats_dense":
        # Statistics grid
        headline_font = get_font(int(canvas_size * 0.07), bold=True)
        draw.text((pad_x, text_y), post.headline, font=headline_font, fill=white)
        text_y += int(canvas_size * 0.09)
        
        if post.stats:
            stat_font = get_font(int(canvas_size * 0.045), bold=True)
            stat_desc_font = get_font(int(canvas_size * 0.022))
            col_width = (canvas_size - pad_x * 2) // 2
            for i, (key, value) in enumerate(list(post.stats.items())[:4]):
                col = i % 2
                row = i // 2
                stat_x = pad_x + (col * col_width)
                stat_y = text_y + (row * int(canvas_size * 0.09))
                draw.text((stat_x, stat_y), str(value), font=stat_font, fill=accent_rgb)
                draw.text((stat_x, stat_y + int(canvas_size * 0.04)), key.replace('_', ' ').title(), 
                         font=stat_desc_font, fill=(*white, 200))
            text_y += int(canvas_size * 0.2)
    else:
        # Standard layout
        headline_font = get_font(int(canvas_size * 0.06), bold=True)
        draw.text((pad_x, text_y), post.headline, font=headline_font, fill=white)
        text_y += int(canvas_size * 0.09)
        
        support_font = get_font(int(canvas_size * 0.03))
        wrapped = wrap(post.supporting_text, width=35)
        for line in wrapped[:3]:
            draw.text((pad_x, text_y), line, font=support_font, fill=(*white, 220))
            text_y += int(canvas_size * 0.042)
    
    # CTA BUTTON
    cta_font = get_font(int(canvas_size * 0.025), bold=True)
    cta_w = int(draw.textlength(post.cta, font=cta_font)) + int(canvas_size * 0.06)
    cta_h = int(canvas_size * 0.055)
    
    cta_x = pad_x
    cta_y = content_bottom - cta_h - int(canvas_size * 0.04)
    
    if layout_strategy == "hero_centered":
        cta_x = (canvas_size - cta_w) // 2
    
    cta_rect = [cta_x, cta_y, cta_x + cta_w, cta_y + cta_h]
    draw.rounded_rectangle(cta_rect, radius=int(cta_h * 0.4), fill=accent_rgb)
    draw.text(
        (cta_x + int(canvas_size * 0.03), cta_y + int(cta_h * 0.2)),
        post.cta, font=cta_font, fill=white
    )
    
    final = bg.convert("RGB")
    final.save(out_path, "JPEG", quality=92)
    return out_path


# ---------------------------------------------------------------------------
# Provider Selection (unchanged from your working code)
# ---------------------------------------------------------------------------

async def select_gemini_key() -> tuple[str, str]:
    print("\n🔑 SELECT GEMINI API KEY:")
    print("-"*50)
    print(f"1. Primary Key {('(starts with: ' + GEMINI_KEY[:15] + '...)') if GEMINI_KEY else '(NOT SET)'}")
    print(f"2. Secondary Key {('(starts with: ' + GEMINI_KEY2[:15] + '...)') if GEMINI_KEY2 else '(NOT SET)'}")
    while True:
        choice = input("\nYour choice [1-2] (default 1): ").strip() or "1"
        if choice == "1" and GEMINI_KEY:
            return (GEMINI_KEY, "Primary")
        elif choice == "2" and GEMINI_KEY2:
            return (GEMINI_KEY2, "Secondary")
        print("  Invalid or key not set")


async def select_openrouter_key() -> tuple[str, str]:
    print("\n🔑 SELECT OPENROUTER API KEY:")
    print("-"*50)
    print(f"1. Primary Key {('(starts with: ' + OPENROUTER_KEY[:15] + '...)') if OPENROUTER_KEY else '(NOT SET)'}")
    print(f"2. Secondary Key {('(starts with: ' + OPENROUTER_KEY2[:15] + '...)') if OPENROUTER_KEY2 else '(NOT SET)'}")
    while True:
        choice = input("\nYour choice [1-2] (default 1): ").strip() or "1"
        if choice == "1" and OPENROUTER_KEY:
            return (OPENROUTER_KEY, "Primary")
        elif choice == "2" and OPENROUTER_KEY2:
            return (OPENROUTER_KEY2, "Secondary")
        print("  Invalid or key not set")


async def select_image_provider() -> tuple[str, str, str]:
    print("\n" + "=" * 60)
    print("  IMAGE GENERATION PROVIDERS")
    print("=" * 60)
    print("  1. Gemini (2 API keys)")
    print("  2. OpenAI DALL-E 3")
    print("  3. MiniMax")
    print("  4. Z.AI")
    print("  5. OpenRouter (2 API keys)")
    print("-" * 60)
    
    provider_map = {"1": "gemini", "2": "openai", "3": "minimax", "4": "zai", "5": "openrouter"}
    name_map = {"gemini": "Gemini", "openai": "OpenAI DALL-E 3", "minimax": "MiniMax", "zai": "Z.AI", "openrouter": "OpenRouter"}
    
    while True:
        choice = input("\nYour choice [1-5] (default 1): ").strip() or "1"
        if choice in provider_map:
            provider = provider_map[choice]
            if provider == "gemini":
                key, key_name = await select_gemini_key()
                return (provider, f"{name_map[provider]} ({key_name} Key)", key)
            elif provider == "openrouter":
                key, key_name = await select_openrouter_key()
                return (provider, f"{name_map[provider]} ({key_name} Key)", key)
            else:
                return (provider, name_map[provider], None)
        print("  Invalid choice")


async def generate_image_with_provider(provider: str, prompt: str, api_key: str = None) -> bytes:
    if provider == "gemini":
        return await GeminiImageGenerator.generate(prompt, api_key, "1:1")
    elif provider == "openai":
        return await OpenAIImageGenerator.generate(prompt, OPENAI_KEY, "1:1")
    elif provider == "minimax":
        return await MiniMaxImageGenerator.generate(prompt, MINIMAX_KEY, "1:1")
    elif provider == "zai":
        return await ZAIImageGenerator.generate(prompt, ZAI_KEY, "1:1")
    elif provider == "openrouter":
        return await OpenRouterImageGenerator.generate(prompt, api_key, "1:1")
    raise RuntimeError(f"Unknown provider: {provider}")


# ---------------------------------------------------------------------------
# Main Campaign Generation
# ---------------------------------------------------------------------------

async def run_campaign(brand: BrandCore, goal: CampaignGoal, image_provider: str, image_api_key: str = None) -> ListType[GeneratedPost]:
    """Full campaign generation - DeepSeek does ALL the creative work"""
    
    print("\n" + "="*70)
    print("  🧠 DEEPSEEK - CREATIVE DIRECTOR MODE")
    print("="*70)
    
    # Step 1: Research and understand the company
    print("\n📊 [1/5] Analyzing brand and campaign context...")
    context = await research_company_context(brand, goal)
    print(f"      ✓ Voice: {context.get('company_voice', '')[:60]}...")
    print(f"      ✓ Differentiators: {context.get('differentiators', '')[:50]}...")
    
    # Step 2: Generate post concepts
    print(f"\n💡 [2/5] Generating {goal.number_of_posts} creative post concepts...")
    concepts = await generate_post_concepts(brand, goal, context, goal.number_of_posts)
    print(f"      ✓ Generated {len(concepts)} unique concepts")
    
    # Step 3: Enrich each post with details
    print("\n✍️ [3/5] Enriching posts with features, stats, and quotes...")
    enriched_posts = []
    for i, concept in enumerate(concepts, 1):
        print(f"      Post {i}: {concept.get('content_type')} - {concept.get('headline')[:35]}...")
        enriched = await enrich_post_content(concept, brand, goal)
        enriched_posts.append(enriched)
    
    # Step 4: Design visual strategy for each post
    print("\n🎨 [4/5] Creating visual strategies and bible for each post...")
    posts_with_visuals = []
    for i, post in enumerate(enriched_posts, 1):
        print(f"      Post {i}: Determining layout...")
        layout = await determine_layout_strategy(post, brand)
        
        print(f"             Creating visual bible...")
        bible = await create_visual_bible(post, layout, brand, goal)
        
        print(f"             Generating background prompt...")
        bg_prompt = await generate_background_prompt(post, bible, layout, brand)
        
        posts_with_visuals.append({
            **post,
            "layout_strategy": layout.get('layout_strategy'),
            "layout": layout,
            "bible": bible,
            "background_prompt": bg_prompt
        })
    
    # Step 5: Generate images
    print(f"\n🖼️ [5/5] Generating {len(posts_with_visuals)} background images...")
    generated_posts = []
    
    for i, post_data in enumerate(posts_with_visuals, 1):
        print(f"      Post {i}: Generating image for '{post_data.get('headline')[:40]}'...")
        
        try:
            image_bytes = await generate_image_with_provider(image_provider, post_data['background_prompt'], image_api_key)
            
            # Create final post object
            generated_post = GeneratedPost(
                id=i,
                content_type=post_data.get('content_type'),
                headline=post_data.get('headline'),
                supporting_text=post_data.get('supporting_text'),
                cta=post_data.get('cta'),
                visual_description=post_data.get('visual_theme', ''),
                mood=post_data.get('bible', {}).get('mood', ''),
                layout_strategy=post_data.get('layout_strategy', 'standard'),
                background_prompt=post_data['background_prompt'],
                features=post_data.get('features', []),
                stats=post_data.get('stats', {}),
                quote=post_data.get('quote', ''),
                background_image_bytes=image_bytes
            )
            generated_posts.append(generated_post)
            print(f"             ✓ Image generated and stored")
            
        except Exception as e:
            print(f"             ✗ Failed: {e}")
            continue
    
    return generated_posts


async def render_all_posts(posts: ListType[GeneratedPost], brand: BrandCore, output_dir: Path) -> ListType[Path]:
    """Render all posts with consistent brand styling"""
    print(f"\n📐 Rendering {len(posts)} posts with brand styling...")
    
    rendered_paths = []
    for post in posts:
        if post.background_image_bytes:
            safe_name = re.sub(r'[^a-zA-Z0-9]', '_', post.headline.lower())[:30]
            filename = f"{post.id:02d}_{post.content_type}_{safe_name}.jpg"
            out_path = output_dir / filename
            
            render_professional_post(
                post.background_image_bytes,
                post,
                brand,
                post.layout_strategy,
                {"mood": post.mood, "color_palette": [brand.primary_color, brand.secondary_color]},
                out_path
            )
            post.final_path = out_path
            rendered_paths.append(out_path)
            print(f"  ✓ {filename}")
    
    return rendered_paths


async def get_user_input() -> tuple[BrandCore, CampaignGoal]:
    """Interactive input for brand and campaign details"""
    print("\n" + "="*60)
    print("  📝 CAMPAIGN SETUP")
    print("="*60)
    
    use_default = input("\nUse default brand (Trackin)? [Y/n]: ").strip().lower()
    
    if use_default == 'n':
        print("\n--- Enter Brand Information ---")
        company_name = input("Company name: ").strip()
        industry = input("Industry: ").strip()
        primary_color = input("Primary color (hex, e.g., #0057FF): ").strip()
        secondary_color = input("Secondary color (hex, e.g., #FFFFFF): ").strip()
        accent_color = input("Accent color (hex, e.g., #FF6B35): ").strip()
        tagline = input("Tagline: ").strip()
        
        brand = BrandCore(
            company_name=company_name,
            industry=industry,
            primary_color=primary_color,
            secondary_color=secondary_color,
            accent_color=accent_color,
            font_style="Inter",
            brand_tone="Professional",
            visual_style="Modern",
            tagline=tagline,
            website_url=f"WWW.{company_name.upper().replace(' ', '')}.COM",
            target_audience=input("Target audience: ").strip(),
            key_products=input("Key products (comma separated): ").strip().split(','),
            brand_values=input("Brand values (comma separated): ").strip().split(',')
        )
    else:
        brand = DEFAULT_BRAND
        print(f"\n✓ Using default brand: {brand.company_name}")
    
    print("\n--- Campaign Goal ---")
    print("Post types to include: hiring, product_launch, educational, inspirational, case_study, announcement, achievement")
    num_posts = int(input("Number of posts to generate [8]: ").strip() or "8")
    
    goal = CampaignGoal(
        objective=input("Campaign objective [brand_awareness]: ").strip() or "brand_awareness",
        key_messages=[input("Key message #1: ").strip()],
        campaign_tone=input("Campaign tone [Professional]: ").strip() or "Professional",
        target_platform=input("Target platform [LinkedIn]: ").strip() or "LinkedIn",
        number_of_posts=num_posts
    )
    
    # Add more key messages
    more = input("Add another key message? (y/n): ").strip().lower()
    while more == 'y':
        goal.key_messages.append(input("Key message: ").strip())
        more = input("Add another? (y/n): ").strip().lower()
    
    return brand, goal


# ---------------------------------------------------------------------------
# Main Entry Point
# ---------------------------------------------------------------------------

async def main() -> None:
    print("="*70)
    print("  🎨 AI SOCIAL MEDIA CAMPAIGN GENERATOR")
    print("  DeepSeek is your Creative Director")
    print("="*70)
    
    # Get user input or use defaults
    brand, goal = await get_user_input()
    
    # Select image provider
    provider_id, provider_name, api_key = await select_image_provider()
    
    # Create output directory for this campaign
    safe_name = re.sub(r'[^a-zA-Z0-9]', '_', brand.company_name.lower())
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = Path(__file__).parent / "generated_images" / f"{safe_name}_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\n" + "="*70)
    print(f"  🚀 STARTING CAMPAIGN GENERATION")
    print("="*70)
    print(f"  Brand: {brand.company_name}")
    print(f"  Industry: {brand.industry}")
    print(f"  Campaign: {goal.objective}")
    print(f"  Posts: {goal.number_of_posts}")
    print(f"  Image Provider: {provider_name}")
    print(f"  Output: {output_dir}")
    print("="*70)
    
    # Generate campaign (DeepSeek does all creative work)
    generated_posts = await run_campaign(brand, goal, provider_id, api_key)
    
    if not generated_posts:
        print("\n❌ No posts were generated successfully!")
        return
    
    # Render all posts
    rendered_paths = await render_all_posts(generated_posts, brand, output_dir)
    
    # Save campaign summary
    summary = {
        "brand": {
            "name": brand.company_name,
            "industry": brand.industry,
            "tagline": brand.tagline,
            "primary_color": brand.primary_color,
            "website": brand.website_url
        },
        "campaign": {
            "objective": goal.objective,
            "tone": goal.campaign_tone,
            "platform": goal.target_platform,
            "generated_at": datetime.now().isoformat()
        },
        "posts": [
            {
                "id": p.id,
                "content_type": p.content_type,
                "headline": p.headline,
                "cta": p.cta,
                "layout_strategy": p.layout_strategy,
                "mood": p.mood,
                "file": str(p.final_path) if p.final_path else None
            }
            for p in generated_posts
        ]
    }
    
    summary_path = output_dir / "campaign_summary.json"
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    
    print("\n" + "="*70)
    print(f"  ✅ CAMPAIGN COMPLETE!")
    print("="*70)
    print(f"  📁 Location: {output_dir}")
    print(f"  📄 Summary: {summary_path.name}")
    print(f"  🖼️ Posts generated: {len(rendered_paths)}/{goal.number_of_posts}")
    print("\n  Generated posts:")
    for p in generated_posts:
        if p.final_path:
            print(f"    • {p.final_path.name}")
    print("="*70)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n\n⚠️ Cancelled by user")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()